# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FUs0sT9lbJqWCJFg29ng6g6WRo_KsEO
"""

import pandas as pd
import numpy as np

data = pd.read_csv('/content/sample.csv', encoding='latin1')

data.head()

data.info()

data.describe()

data.isnull()

data.isnull().sum()

duplicates=data.duplicated()
print(duplicates.sum())

data=data.drop_duplicates()
#drop duplicates from data if presents

data.columns

data.dtypes

data['Order Date'] = pd.to_datetime(data['Order Date'])

data['Ship Date'] = pd.to_datetime(data['Ship Date'])

data.dtypes

data['Year'] = data['Order Date'].dt.year
data['Month'] = data['Order Date'].dt.month

data['Profit Margin']= (data['Profit'] / data['Sales']) * 100

data.columns

data.head()

data.to_csv('Cleaned_data',index='false')